print("python:     ", __import__("sys").version)
print("numpy:      ", __import__("numpy").__version__)
print("scipy:      ", __import__("scipy").__version__)
print("matplotlib: ", __import__("matplotlib").__version__)
print("argparse:   ", __import__("argparse").__version__)
print("yaml:       ", __import__("yaml").__version__)
print("pandas:     ", __import__("pandas").__version__)
